class MalaysiaStates {
  static const List<String> states = [
    "Kuala Lumpur",
    "Putrajaya",
    "Labuan",
    "Perlis",
    "Kedah",
    "Terengganu",
    "Pahang",
    "Perak",
    "Kelantan",
    "Penang",
    "Selangor",
    "Negeri Sembilan",
    "Johor",
    "Malacca",
    "Sabah",
    "Sarawak",
  ];

  static const List<String> firstNames = [
    'John',
    'Emma',
    'Michael',
    'Sophia',
    'William',
    'Olivia',
    'James',
    'Ava',
    'Alexander',
    'Mia',
    'Benjamin',
    'Charlotte',
    'Ethan',
    'Amelia',
    'Daniel',
    'Harper',
    'Matthew',
    'Evelyn',
    'Joseph',
    'Abigail',
    'David',
    'Emily',
    'Christopher',
    'Elizabeth',
    'Andrew',
    'Sofia',
    'Dylan',
    'Madison',
    'Jacob',
    'Avery',
  ];
}
